#!/usr/bin/env python3
"""
gen_docs.py — LoamLab Tutorial Documentation Generator

Usage:
    python scripts/gen_docs.py --version 1.3.1
    python scripts/gen_docs.py --version 1.3.1 --lang zh-TW
    python scripts/gen_docs.py --version 1.3.1 --patch-landing   (future: patches public/index.html)

Outputs:
    docs/generated/{lang}/README.md
    docs/generated/{lang}/{tool_id}.md
    docs/generated/social/captions.json
    docs/generated/recording_checklist.md
"""

import argparse
import json
import os
import sys
from datetime import datetime

# ── Config ─────────────────────────────────────────────────────────────────────
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(REPO_ROOT, 'docs', 'tutorial_config.json')
OUTPUT_DIR = os.path.join(REPO_ROOT, 'docs', 'generated')

LANG_NAMES = {
    'zh-TW': '繁體中文',
    'en-US': 'English',
    'zh-CN': '简体中文',
    'es-ES': 'Español',
    'pt-BR': 'Português',
    'ja-JP': '日本語',
}

SOCIAL_PLATFORMS = {
    'zh-TW': ['LINE', 'Instagram', 'Facebook'],
    'en-US': ['Twitter/X', 'Instagram', 'LinkedIn'],
    'zh-CN': ['微博', '小红书', '微信'],
    'es-ES': ['Instagram', 'Twitter/X'],
    'pt-BR': ['Instagram', 'WhatsApp'],
    'ja-JP': ['Twitter/X', 'Instagram'],
}


# ── Helpers ────────────────────────────────────────────────────────────────────

def load_config():
    with open(CONFIG_PATH, encoding='utf-8') as f:
        return json.load(f)


def get_lang(obj, lang):
    """Get localized string, fallback to en-US."""
    if not obj:
        return ''
    return obj.get(lang) or obj.get('en-US') or ''


def version_lte(a, b):
    """Return True if version a <= b."""
    def parts(v):
        return [int(x) for x in v.split('.')]
    pa, pb = parts(a), parts(b)
    return pa <= pb


def filter_tools(tools, version):
    """Return live tools whose since <= version."""
    result = []
    for tool in tools:
        if not version_lte(tool.get('since', '0.0.0'), version):
            continue
        if tool.get('deprecated'):
            continue
        result.append(tool)
    return result


def filter_steps(steps, version):
    """Return steps whose since <= version and not deprecated."""
    result = []
    for step in steps:
        if step.get('deprecated'):
            continue
        if not version_lte(step.get('since', '0.0.0'), version):
            continue
        result.append(step)
    return result


def ensure_dir(path):
    os.makedirs(path, exist_ok=True)


# ── Generators ─────────────────────────────────────────────────────────────────

def gen_tool_md(tool, lang, version):
    """Generate markdown for a single tool in a single language."""
    lines = []
    title = get_lang(tool.get('title'), lang)
    short_desc = get_lang(tool.get('short_desc'), lang)
    tagline = get_lang(tool.get('marketing', {}).get('tagline'), lang)
    pts = tool.get('pts_label', '')
    icon = tool.get('icon', '')

    lines.append(f"# {icon} {title}")
    lines.append('')
    lines.append(f"> {tagline}")
    lines.append('')
    lines.append(short_desc)
    lines.append('')
    lines.append(f"**Cost:** {pts}")
    lines.append('')
    lines.append('---')
    lines.append('')
    lines.append('## How to Use')
    lines.append('')

    steps = filter_steps(tool.get('steps', []), version)
    for step in steps:
        step_title = get_lang(step.get('title'), lang)
        step_desc = get_lang(step.get('desc'), lang)
        visual = step.get('visual', {})
        step_icon = visual.get('icon', '📋')
        lines.append(f"### Step {step['step']}: {step_title}")
        lines.append('')
        lines.append(f"{step_icon} {step_desc}")
        lines.append('')

    social_caption = get_lang(tool.get('marketing', {}).get('social_caption'), lang)
    if social_caption:
        lines.append('---')
        lines.append('')
        lines.append('## Social Caption')
        lines.append('')
        lines.append(f'```')
        lines.append(social_caption)
        lines.append(f'```')
        lines.append('')

    lines.append(f'*Generated by gen_docs.py · v{version} · {datetime.now().strftime("%Y-%m-%d")}*')

    return '\n'.join(lines)


def gen_readme(tools, lang, version):
    """Generate README.md index for a language."""
    lines = []
    lang_name = LANG_NAMES.get(lang, lang)
    lines.append(f"# LoamLab — {lang_name}")
    lines.append('')
    lines.append(f"Version: **{version}** · Generated: {datetime.now().strftime('%Y-%m-%d')}")
    lines.append('')
    lines.append('## Tools')
    lines.append('')
    for tool in tools:
        icon = tool.get('icon', '')
        title = get_lang(tool.get('title'), lang)
        short_desc = get_lang(tool.get('short_desc'), lang)
        tool_id = tool.get('id')
        live = tool.get('live', False)
        status = '✓ Live' if live else '⏳ Coming Soon'
        lines.append(f"### {icon} [{title}](./{tool_id}.md)")
        lines.append(f"{short_desc}")
        lines.append('')
        lines.append(f"**Status:** {status}  |  **Cost:** {tool.get('pts_label', '')}")
        lines.append('')

    return '\n'.join(lines)


def gen_social_captions(tools, all_langs, version):
    """Generate a JSON file with social captions per tool per language."""
    result = {}
    for tool in tools:
        tool_id = tool.get('id')
        result[tool_id] = {
            'title': tool.get('title', {}),
            'tagline': tool.get('marketing', {}).get('tagline', {}),
            'captions': tool.get('marketing', {}).get('social_caption', {}),
            'platforms': {lang: SOCIAL_PLATFORMS.get(lang, []) for lang in all_langs},
        }
    return result


def gen_recording_checklist(tools, lang, version):
    """Generate a markdown recording checklist for human GIF capture."""
    lines = []
    lines.append('# GIF Recording Checklist')
    lines.append('')
    lines.append(f'> Auto-generated · v{version} · {datetime.now().strftime("%Y-%m-%d")}')
    lines.append('> Follow each checklist to record a GIF for the corresponding tool.')
    lines.append('')

    for tool in tools:
        icon = tool.get('icon', '')
        title = get_lang(tool.get('title'), lang)
        gif_file = tool.get('marketing', {}).get('gif_filename', f"{tool['id']}-demo.gif")
        steps = filter_steps(tool.get('steps', []), version)

        lines.append(f"## {icon} {title}")
        lines.append('')
        lines.append(f'**Output file:** `docs/assets/gifs/{gif_file}`')
        lines.append('')
        lines.append('**Setup:**')
        lines.append('- [ ] Open SketchUp with a sample 3D model')
        lines.append('- [ ] Open LoamLab plugin (DEV version is fine)')
        lines.append('- [ ] Set screen recording to 1280×720 or 1920×1080')
        lines.append('- [ ] Recommended GIF duration: 8–15 seconds, looping')
        lines.append('')
        lines.append('**Recording steps:**')

        for step in steps:
            step_title = get_lang(step.get('title'), lang)
            step_desc = get_lang(step.get('desc'), lang)
            visual = step.get('visual', {})
            highlight = visual.get('highlight_area', '')
            lines.append(f'- [ ] **{step_title}** — {step_desc}')
            if highlight:
                lines.append(f'  *(Highlight area: `{highlight}`)*')

        lines.append(f'- [ ] Export as GIF → save to `docs/assets/gifs/{gif_file}`')
        lines.append('')

    lines.append('---')
    lines.append('*Tip: Use LICEcap, ScreenToGif, or ShareX to record and export GIFs.*')

    return '\n'.join(lines)


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description='Generate LoamLab tutorial documentation')
    parser.add_argument('--version', required=True, help='Plugin version (e.g. 1.3.1)')
    parser.add_argument('--lang', default=None, help='Single language to generate (default: all)')
    parser.add_argument('--patch-landing', action='store_true', help='(Future) Patch public/index.html FeaturesConfig')
    args = parser.parse_args()

    version = args.version
    target_langs = [args.lang] if args.lang else list(LANG_NAMES.keys())

    # Load config
    if not os.path.exists(CONFIG_PATH):
        print(f'[ERROR] tutorial_config.json not found at {CONFIG_PATH}', file=sys.stderr)
        sys.exit(1)

    config = load_config()
    all_tools = config.get('tools', [])
    live_tools = filter_tools(all_tools, version)

    print(f'[gen_docs] v{version} | {len(live_tools)} tools | {len(target_langs)} languages')

    # Per-language markdown
    for lang in target_langs:
        lang_dir = os.path.join(OUTPUT_DIR, lang)
        ensure_dir(lang_dir)

        # README
        readme = gen_readme(live_tools, lang, version)
        with open(os.path.join(lang_dir, 'README.md'), 'w', encoding='utf-8') as f:
            f.write(readme)

        # Per-tool pages
        for tool in live_tools:
            tool_md = gen_tool_md(tool, lang, version)
            fname = f"{tool['id']}.md"
            with open(os.path.join(lang_dir, fname), 'w', encoding='utf-8') as f:
                f.write(tool_md)

        print(f'  [{lang}] {len(live_tools) + 1} files written → docs/generated/{lang}/')

    # Social captions JSON
    social_dir = os.path.join(OUTPUT_DIR, 'social')
    ensure_dir(social_dir)
    captions = gen_social_captions(live_tools, target_langs, version)
    with open(os.path.join(social_dir, 'captions.json'), 'w', encoding='utf-8') as f:
        json.dump(captions, f, ensure_ascii=False, indent=2)
    print(f'  [social] captions.json written')

    # Recording checklist (English)
    checklist = gen_recording_checklist(live_tools, 'en-US', version)
    with open(os.path.join(OUTPUT_DIR, 'recording_checklist.md'), 'w', encoding='utf-8') as f:
        f.write(checklist)
    print(f'  [checklist] recording_checklist.md written')

    # Future: --patch-landing
    if args.patch_landing:
        print('  [landing] --patch-landing not yet implemented (safe to skip)')

    print(f'[gen_docs] Done. Output: docs/generated/')


if __name__ == '__main__':
    main()
